# path to dataset
data_path: "olympics2024.csv"

save_plots: "artifacts/analysis_plots"
trends: "artifacts/analysis_plots/trends"
bivariate: "artifacts/analysis_plots/bivariate"
distribution: "artifacts/analysis_plots/distribution"
correlation: "artifacts/analysis_plots/correlation_matrix.png"
pca_summary: "artifacts/analysis_plots/pca_analysis.png"
feature_imp: "artifacts/analysis_plots/feature_importance_plot.png"